name: SP500 数据增量更新

on:
  # 定时任务（每天北京时间21点）
  schedule:
    - cron: '0 21 * * *'
  # 手动触发
  workflow_dispatch:
  # push 到 main 分支也触发
  push:
    branches: [main]

jobs:
  update-sp500:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          pip install pandas requests beautifulsoup4 yfinance fake_useragent

      - name: 运行原 Python 脚本
        run: python sp500_data.py

      - name: 增量追加新数据到 CSV
        run: python append_new_data.py

      - name: 提交更新后的 CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sp500_data/*.csv
          git diff --quiet && echo "CSV 无更新，跳过提交" || git commit -m "增量更新 SP500 CSV"
          git push

        
