name: SP500 Data Update

on:
  schedule:            # 定时任务 (每天北京时间 8:00 运行)
    - cron: '0 0 * * *'   # UTC 时间 0:00 (换算成北京时间 8:00)
  workflow_dispatch:   # 手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:       # 确保 GitHub Token 有写入权限
      contents: write

    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 运行原Python脚本
        run: |
          python sp500_data.py

      - name: 运行增量追加脚本
        run: |
          python append_new_data.py

      - name: 提交更新后的CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add sp500_data/*.csv

          if git diff --cached --quiet; then
            echo "⚠️ CSV 无更新，跳过提交"
          else
            git commit -m "增量更新 SP500 CSV"
            git push origin HEAD:main
            echo "✅ CSV 已更新并推送成功"
          fi

      - name: 运行缠论处理脚本
        run: |
          python chan_processor.py

      - name: 提交更新后的数据文件
        run: |
          # 配置 Git 用户信息
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      
          # 添加文件（存在的才 add，不存在不会报错）
          git add sp500_data/*.csv 2>/dev/null || true
          git add processed_data/*.csv 2>/dev/null || true
          git add sequence_data/*.csv 2>/dev/null || true
          git add sequence_data/*.json 2>/dev/null || true
          git add state/*.json 2>/dev/null || true
      
          # 如果没有更新，直接跳过
          if git diff --cached --quiet; then
            echo "⚠️ 没有新数据需要提交，跳过"
          else
            # 拉取远程最新提交，使用 rebase 避免冲突
            git pull --rebase origin main || true
      
            # 提交并推送
            git commit -m "增量更新 SP500 和缠论处理数据"
            git push origin HEAD:main
            echo "✅ 数据已更新并推送成功"
          fi
            
